[package]
name = "solidpython_config"
version = "0.1.0"
edition = "2021"
default-run = "solidpython_config"

# create default-run
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
man = "0.3.0"
